modLoader="javafml"

loaderVersion="[4,)"

license="MIT"

issueTrackerURL="https://github.com/BlizertWarrior/Elytra-Booster-Mod-Neo-Forge/issues"

[[mods]]

modId="elytraboostermod"
version="[1.21.1]"
displayName="Elytra Booster Mod"
logoFile="ElytraBoosterModLogo.png"
authors="BlizertWarrior"
description="Adds a vehicle upgrade for Immersive Aircrafts that (should) buff the planes to be a good contender to the elytra!"

[[dependencies.elytraboostermod]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.elytraboostermod]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.elytraboostermod]]
modId="immersive_aircraft"
type="required"
versionRange="${immersive_aircraft_version}"
ordering="AFTER"
side="BOTH"

